i# .github/workflows/playwright.yml
name: Playwright Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run tests via Docker Compose
        run: docker-compose up --build --abort-on-container-exit
      - name: Upload HTML Report
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: test-results/

