name: Playwright Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build and run Playwright tests
        run: docker compose up --build --abort-on-container-exit

      - name: Upload HTML Report
        if: always()  # Always run even if tests fail
        uses: actions/upload-artifact@v4
        with:
          name: playwright-html-report
          path: test-results/


